import type { LanguageCode } from "./i18n";

const en = {
  skipToContent: "Skip to main content",
  mainContent: "Main content",
  appNavigation: "Main navigation",
  showPassword: "Show password",
  hidePassword: "Hide password",
  closeDialog: "Close dialog",
  clearSearch: "Clear search",
  refresh: "Refresh",
  increase: "Increase",
  decrease: "Decrease",
  previousMonth: "Previous month",
  nextMonth: "Next month",
  opensNewWindow: "Opens in a new window",
  hour: "Hour",
  minute: "Minute",
  reduceMotion: "Reduce motion",
  loading: "Loading",
};

export type AccessibilityLabels = { [K in keyof typeof en]: string };

export const accessibilityCopy = {
  en,
  fr: {
    skipToContent: "Aller au contenu principal", mainContent: "Contenu principal",
    appNavigation: "Navigation principale", showPassword: "Afficher le mot de passe",
    hidePassword: "Masquer le mot de passe", closeDialog: "Fermer la boîte de dialogue",
    clearSearch: "Effacer la recherche", refresh: "Actualiser", increase: "Augmenter",
    decrease: "Diminuer", previousMonth: "Mois précédent", nextMonth: "Mois suivant",
    opensNewWindow: "S’ouvre dans une nouvelle fenêtre", hour: "Heure", minute: "Minute",
    reduceMotion: "Réduire les animations", loading: "Chargement",
  },
  es: {
    skipToContent: "Saltar al contenido principal", mainContent: "Contenido principal",
    appNavigation: "Navegación principal", showPassword: "Mostrar contraseña",
    hidePassword: "Ocultar contraseña", closeDialog: "Cerrar diálogo",
    clearSearch: "Borrar búsqueda", refresh: "Actualizar", increase: "Aumentar",
    decrease: "Disminuir", previousMonth: "Mes anterior", nextMonth: "Mes siguiente",
    opensNewWindow: "Se abre en una ventana nueva", hour: "Hora", minute: "Minuto",
    reduceMotion: "Reducir movimiento", loading: "Cargando",
  },
  pt: {
    skipToContent: "Ir para o conteúdo principal", mainContent: "Conteúdo principal",
    appNavigation: "Navegação principal", showPassword: "Mostrar palavra-passe",
    hidePassword: "Ocultar palavra-passe", closeDialog: "Fechar diálogo",
    clearSearch: "Limpar pesquisa", refresh: "Atualizar", increase: "Aumentar",
    decrease: "Diminuir", previousMonth: "Mês anterior", nextMonth: "Mês seguinte",
    opensNewWindow: "Abre numa nova janela", hour: "Hora", minute: "Minuto",
    reduceMotion: "Reduzir movimento", loading: "A carregar",
  },
  ar: {
    skipToContent: "الانتقال إلى المحتوى الرئيسي", mainContent: "المحتوى الرئيسي",
    appNavigation: "التنقل الرئيسي", showPassword: "إظهار كلمة المرور",
    hidePassword: "إخفاء كلمة المرور", closeDialog: "إغلاق مربع الحوار",
    clearSearch: "مسح البحث", refresh: "تحديث", increase: "زيادة",
    decrease: "تقليل", previousMonth: "الشهر السابق", nextMonth: "الشهر التالي",
    opensNewWindow: "يفتح في نافذة جديدة", hour: "الساعة", minute: "الدقيقة",
    reduceMotion: "تقليل الحركة", loading: "جارٍ التحميل",
  },
  zh: {
    skipToContent: "跳转到主要内容", mainContent: "主要内容", appNavigation: "主导航",
    showPassword: "显示密码", hidePassword: "隐藏密码", closeDialog: "关闭对话框",
    clearSearch: "清除搜索", refresh: "刷新", increase: "增加", decrease: "减少",
    previousMonth: "上个月", nextMonth: "下个月", opensNewWindow: "在新窗口中打开",
    hour: "小时", minute: "分钟", reduceMotion: "减少动态效果", loading: "正在加载",
  },
  de: {
    skipToContent: "Zum Hauptinhalt springen", mainContent: "Hauptinhalt",
    appNavigation: "Hauptnavigation", showPassword: "Passwort anzeigen",
    hidePassword: "Passwort verbergen", closeDialog: "Dialog schließen",
    clearSearch: "Suche löschen", refresh: "Aktualisieren", increase: "Erhöhen",
    decrease: "Verringern", previousMonth: "Vorheriger Monat", nextMonth: "Nächster Monat",
    opensNewWindow: "Öffnet in einem neuen Fenster", hour: "Stunde", minute: "Minute",
    reduceMotion: "Bewegung reduzieren", loading: "Wird geladen",
  },
  it: {
    skipToContent: "Vai al contenuto principale", mainContent: "Contenuto principale",
    appNavigation: "Navigazione principale", showPassword: "Mostra password",
    hidePassword: "Nascondi password", closeDialog: "Chiudi finestra di dialogo",
    clearSearch: "Cancella ricerca", refresh: "Aggiorna", increase: "Aumenta",
    decrease: "Diminuisci", previousMonth: "Mese precedente", nextMonth: "Mese successivo",
    opensNewWindow: "Si apre in una nuova finestra", hour: "Ora", minute: "Minuto",
    reduceMotion: "Riduci movimento", loading: "Caricamento",
  },
  ja: {
    skipToContent: "メインコンテンツへ移動", mainContent: "メインコンテンツ",
    appNavigation: "メインナビゲーション", showPassword: "パスワードを表示",
    hidePassword: "パスワードを非表示", closeDialog: "ダイアログを閉じる",
    clearSearch: "検索をクリア", refresh: "更新", increase: "増やす", decrease: "減らす",
    previousMonth: "前の月", nextMonth: "次の月", opensNewWindow: "新しいウィンドウで開きます",
    hour: "時", minute: "分", reduceMotion: "動きを減らす", loading: "読み込み中",
  },
  ko: {
    skipToContent: "본문으로 건너뛰기", mainContent: "본문", appNavigation: "주 탐색",
    showPassword: "비밀번호 표시", hidePassword: "비밀번호 숨기기", closeDialog: "대화상자 닫기",
    clearSearch: "검색 지우기", refresh: "새로 고침", increase: "늘리기", decrease: "줄이기",
    previousMonth: "이전 달", nextMonth: "다음 달", opensNewWindow: "새 창에서 열립니다",
    hour: "시", minute: "분", reduceMotion: "동작 줄이기", loading: "불러오는 중",
  },
} satisfies Record<LanguageCode, AccessibilityLabels>;