// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/carnet-home/Current.tsx": () => import("../components/mockups/carnet-home/Current.tsx"),
  "./components/mockups/carnet-home/MyChartResponsive.tsx": () => import("../components/mockups/carnet-home/MyChartResponsive.tsx")
};
